name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  install-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --immutable
      
      - name: cat yarn.lock
        run: cat yarn.lock

  install-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --immutable

      - name: cat yarn.lock
        run: cat yarn.lock
